// Load your images on page-load
function preloader() {
    const imagesList = [
        "./img/img-1.jpg",
        "./img/img-2.jpg",
        "./img/img-3.jpg"
    ];
    const images = [];
    for (let i = 0; i < imagesList.length; i++) {
        images[i] = new Image();
        images[i].src = imagesList[i];
    }

    // Images ready to be used:
    console.log(`Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
};
window.addEventListener("load", preloader);

// Get all buttons in a NODE LIST of buttons (array-like structure)
const buttons = document.querySelectorAll('#trigger-buttons button');

// Resource object to store dynamic content
const resourceObject = [
    {
        headingContent: "Hydroelectricity",
        bodyText: "Hydroelectricity is a renewable energy source that utilizes the kinetic energy of flowing or falling water to generate electricity through the operation of turbines. The cost of hydroelectricity varies depending on factors such as the scale of the project, geographical location, environmental considerations, and construction expenses. While large-scale hydroelectric projects may entail substantial upfront costs for dam construction and associated infrastructure, they often offer long-term benefits with relatively low operating expenses over their lifespan. Conversely, smaller-scale hydroelectric projects can be more cost-effective to implement and maintain. Nonetheless, the development of hydroelectric facilities must also account for environmental impacts, such as habitat disruption and alterations in water flow patterns, as well as social considerations, including the potential displacement of communities, which can influence overall project costs. //Generated by ChatGTP.",
        imgUrl: "./img/img-1.jpg",
        imgAlt: "A hydropower station"
    },
    {
        headingContent: "Solar Power",
        bodyText: "Solar power refers to the conversion of sunlight into electricity using photovoltaic cells or solar thermal systems. Photovoltaic cells directly convert sunlight into electricity, while solar thermal systems use sunlight to heat a fluid that produces steam to drive turbines and generate electricity. The cost of solar power depends on various factors such as the type of solar technology used, installation costs, location, government incentives, and financing options. Generally, the cost of solar power has been decreasing over the years due to advancements in technology and economies of scale. In many regions, solar power has become increasingly competitive with traditional sources of electricity, making it an attractive option for both residential and commercial applications. //Generated by ChatGTP.",
        imgUrl: "./img/img-2.jpg",
        imgAlt: "A pile of solar panels"
    },
    {
        headingContent: "Wind Power",
        bodyText: "Wind power involves harnessing the kinetic energy of the wind to generate electricity using wind turbines. These turbines consist of blades mounted on a tower, which spin as wind passes through them, driving a generator to produce electricity. The cost of wind power can vary depending on factors such as the location and quality of wind resources, turbine technology, installation expenses, and ongoing maintenance costs. Generally, onshore wind farms tend to have lower costs compared to offshore installations due to easier accessibility and simpler construction processes. However, offshore wind farms can harness stronger and more consistent winds, potentially increasing their energy output and offsetting higher initial investments. Overall, advancements in wind turbine technology and economies of scale have contributed to a significant reduction in the cost of wind power, making it increasingly competitive with other forms of electricity generation. //Generated by ChatGTP.",
        imgUrl: "./img/img-3.jpg",
        imgAlt: "Windmills under sunset"
    }
];

// Get reference to HTML-container for dynamic loading
const dynamicContentContainer = document.getElementById('dynamic-content');

// Initial content loaded on page load
dynamicContentContainer.innerHTML = `
    <h1>${resourceObject[0].headingContent}</h1>
    <img src="${resourceObject[0].imgUrl}" alt="${resourceObject[0].imgAlt}">
    <p>${resourceObject[0].bodyText}</p>
`;

// Function to handle button clicks and load dynamic content
function handleSelection(event) {
    // Remove active class from all buttons
    buttons.forEach(button => {
        button.classList.remove('active');
    });

    // Set the clicked button as active
    event.target.classList.add('active');

    // Get the index of the clicked button
    const index = Array.from(buttons).indexOf(event.target);

    // Generate HTML content for the selected solution
    const htmlContent = `
        <h1>${resourceObject[index].headingContent}</h1>
        <img src="${resourceObject[index].imgUrl}" alt="${resourceObject[index].imgAlt}">
        <p>${resourceObject[index].bodyText}</p>
    `;

    // Assign the generated HTML content to the dynamic content container
    dynamicContentContainer.innerHTML = htmlContent;
}

// Register all buttons to click event
buttons.forEach(button => {
    button.addEventListener('click', handleSelection);
});
